# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angkatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kenalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KenalanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('birth_place', models.CharField(max_length=50, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('asal_sma', models.CharField(max_length=50)),
                ('story', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kenalan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kenalan.Kenalan')),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KenalanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='uploads/')),
                ('about', models.TextField(null=True)),
                ('linkedin', models.CharField(max_length=50, null=True)),
                ('facebook', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('birth_place', models.CharField(max_length=50, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('npm', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('angkatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kenalan.Angkatan')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kenalan.Profile')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kenalan.Role')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='kenalan.User'),
        ),
        migrations.AddField(
            model_name='kenalandetail',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kenalan.KenalanStatus'),
        ),
        migrations.AddField(
            model_name='kenalan',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kenalan.Token'),
        ),
        migrations.AddField(
            model_name='kenalan',
            name='user1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='kenalan.User'),
        ),
        migrations.AddField(
            model_name='kenalan',
            name='user2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='kenalan.User'),
        ),
    ]
