# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kenalan.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailKenalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('birth_place', models.CharField(max_length=50, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('asal_sma', models.CharField(max_length=50, null=True)),
                ('story', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Kenalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KenalanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(default=kenalan.models.default_end_time)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['token'],
            },
        ),
        migrations.AddField(
            model_name='kenalan',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='kenalan.KenalanStatus'),
        ),
        migrations.AddField(
            model_name='kenalan',
            name='user_elemen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_elemen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kenalan',
            name='user_maba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_maba', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailkenalan',
            name='kenalan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_kenalan', to='kenalan.Kenalan'),
        ),
        migrations.AlterUniqueTogether(
            name='kenalan',
            unique_together=set([('user_elemen', 'user_maba')]),
        ),
    ]
