# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenalan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KenalanDetail',
            new_name='DetailKenalan',
        ),
    ]
