# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kenalan', '0002_auto_20170717_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailkenalan',
            name='kenalan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_kenalan', to='kenalan.Kenalan'),
        ),
        migrations.AlterUniqueTogether(
            name='kenalan',
            unique_together=set([('user_elemen', 'user_maba')]),
        ),
    ]
