# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kenalan', '0002_auto_20170717_2212'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kenalan',
            unique_together=set([('user_elemen', 'user_maba')]),
        ),
    ]
