# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kenalan', '0002_auto_20170611_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kenalan',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenalan.Token'),
        ),
        migrations.AlterField(
            model_name='kenalan',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='kenalan.User'),
        ),
        migrations.AlterField(
            model_name='kenalan',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='kenalan.User'),
        ),
        migrations.AlterField(
            model_name='kenalandetail',
            name='kenalan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenalan.Kenalan'),
        ),
        migrations.AlterField(
            model_name='kenalandetail',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenalan.KenalanStatus'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kenalan.User'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kenalan.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='angkatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenalan.Angkatan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenalan.Role'),
        ),
    ]
