# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kenalan', '0003_auto_20170719_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailkenalan',
            name='kenalan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_kenalan', to='kenalan.Kenalan'),
        ),
    ]
