# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenalan', '0004_auto_20170704_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['token']},
        ),
    ]
