# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 03:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kenalan', '0005_auto_20170704_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('npm', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('photo', models.ImageField(null=True, upload_to='uploads/')),
                ('about', models.TextField(null=True)),
                ('linkedin', models.CharField(max_length=50, null=True)),
                ('facebook', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('birth_place', models.CharField(max_length=50, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('angkatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenalan.Angkatan')),
                ('role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kenalan.Role')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='angkatan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterModelOptions(
            name='kenalan',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='kenalan',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kenalan',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='kenalan',
            unique_together=set([('token', 'user1')]),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
