# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenalan', '0006_auto_20170705_0356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kenalan',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='kenalan',
            name='token',
        ),
    ]
