# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenalan', '0007_auto_20170706_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_time', models.DateTimeField(auto_now_add=True)),
                ('token', models.IntegerField()),
            ],
            options={
                'ordering': ['expire_time'],
            },
        ),
    ]
