# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenalan', '0010_auto_20170711_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpiredToken',
        ),
    ]
