# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kenalan', '0012_auto_20170711_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kenalan',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='kenalan',
            name='user2',
        ),
        migrations.AddField(
            model_name='kenalan',
            name='user_elemen',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_elemen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kenalan',
            name='user_maba',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_maba', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kenalandetail',
            name='asal_sma',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kenalandetail',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kenalandetail',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kenalandetail',
            name='story',
            field=models.TextField(null=True),
        ),
    ]
