# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170727_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='media'),
        ),
    ]
