# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='events',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='task',
            name='submission',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
