# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_auto_20170727_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('album_link', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.SmallIntegerField(default=0)),
                ('on_time', models.SmallIntegerField(default=0)),
                ('late', models.SmallIntegerField(default=0)),
                ('permission', models.SmallIntegerField(default=0)),
                ('absent', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KenalanStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.SmallIntegerField(default=0)),
                ('amount', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='events',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AddField(
            model_name='event',
            name='attachment_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_kenalan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
        migrations.AddField(
            model_name='taskstatistic',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='website.Task'),
        ),
        migrations.AddField(
            model_name='kenalanstatistic',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Task'),
        ),
        migrations.AddField(
            model_name='kenalanstatistic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kenalan_statistics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventstatistic',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Event'),
        ),
    ]
