# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_auto_20170727_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expected_amount', models.SmallIntegerField(default=0)),
                ('amount', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='kenalanstatistic',
            name='task',
        ),
        migrations.RemoveField(
            model_name='kenalanstatistic',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='attachment_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskstatistic',
            name='expected_amount',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='KenalanStatistic',
        ),
    ]
