# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170727_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
