# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_auto_20170730_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expected_amount', models.SmallIntegerField(default=0)),
                ('amount', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='kenalanstatistic',
            name='task',
        ),
        migrations.RemoveField(
            model_name='kenalanstatistic',
            name='user',
        ),
        migrations.DeleteModel(
            name='KenalanStatistic',
        ),
    ]
