# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170730_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatistic',
            name='expected_amount',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
