# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170730_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Task'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
