# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170730_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistic',
            name='amount_approved_alumni',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='amount_approved_capung',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='amount_approved_omega',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='amount_approved_orion',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
