# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170730_2003'),
        ('website', '0006_auto_20170730_1405'),
    ]

    operations = [
    ]
