# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170801_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatistic',
            name='amount_alumni',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='amount_approved_alumni',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='amount_approved_capung',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='amount_approved_omega',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='amount_approved_orion',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='amount_capung',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='amount_omega',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='amount_orion',
            field=models.SmallIntegerField(default=0),
        ),
    ]
